// NOTIFICATION ACTION TYPES
export const GET_ERRORS = "GET_ERRORS";

// AUTH ACTION TYPES
export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_LOADED = "AUTH_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL";
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS";
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS";
export const AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL";

// HOME ACTION TYPES
export const GET_HOME_SUCCESS = "GET_HOME_SUCCESS";

// CART ACTION TYPES
export const GET_CART = "GET_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL";
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS";
export const REMOVE_FROM_CART_FAIL = "REMOVE_FROM_CART_FAIL";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAIL = "UPDATE_CART_FAIL";
export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS";
export const CLEAR_CART_FAIL = "CLEAR_CART_FAIL";

// WISHLIST ACTION TYPES
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST";
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS";
export const ADD_TO_WISHLIST_FAIL = "ADD_TO_WISHLIST_FAIL";
export const REMOVE_FROM_WISHLIST_SUCCESS = "REMOVE_FROM_WISHLIST_SUCCESS";
export const REMOVE_FROM_WISHLIST_FAIL = "REMOVE_FROM_WISHLIST_FAIL";
export const CLEAR_WISHLIST_SUCCESS = "CLEAR_WISHLIST_SUCCESS";
export const CLEAR_WISHLIST_FAIL = "CLEAR_WISHLIST_FAIL";


// ORDER ACTION TYPES
export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDER_PRODUCTS = "GET_ORDER_PRODUCTS";
export const ORDER_PALCE_SUCCESS = "ORDER_PLACE_SUCCESS";
export const ORDER_PALCE_FAIL = "ORDER_PLACE_FAIL";
export const ORDER_RETURN_SUCCESS = "ORDER_RETURN_SUCCESS";
export const ORDER_RETURN_FAIL = "ORDER_RETURN_FAIL";
export const QUICK_BUY_SUCCESS = "QUICK_BUY_SUCCESS";
export const QUICK_BUY_FAIL = "QUICK_BUY_FAIL";

// PRODUCT ACTION TYPES
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
export const GET_RELATED_PRODUCTS_SUCCESS = "GET_RELATED_PRODUCTS_SUCCESS";
export const GET_RELATED_PRODUCTS_FAIL = "GET_RELATED_PRODUCTS_FAIL";
export const GET_PRODUCT_SUGGESTIONS_SUCCESS = "GET_PRODUCT_SUGGESTIONS_SUCCESS";
export const GET_PRODUCT_SUGGESTIONS_FAIL = "GET_PRODUCT_SUGGESTIONS_FAIL";


// SUBSCRIBE ACTION TYPES
export const SUBSCRIBED_SUCCESS = "SUBSCRIBED_SUCCESS";
export const UNSUBSCRIBED_SUCCESS = "UNSUBSCRIBED_SUCCESS";
