// NOTIFICATION ACTION TYPES
export const GET_ERRORS = "GET_ERRORS"

// AUTH ACTION TYPES
export const AUTH_LOADING = "AUTH_LOADING"
export const AUTH_LOADED = "AUTH_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const AUTH_TEMP_PASS_SUCESS = "AUTH_TEMP_PASS_SUCESS"
export const AUTH_TEMP_PASS_FAIL = "AUTH_TEMP_PASS_FAIL"
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL"
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS"
export const AUTH_REGISTER_SUCCESS = "AUTH_REGISTER_SUCCESS"
export const AUTH_REGISTER_FAIL = "AUTH_REGISTER_FAIL"
// export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS"
// export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL"

// REQUEST ACTION TYPES
export const GET_ANALYSIS = "GET_ANALYSIS"
export const SUBMIT_REQUEST = "SUBMIT_REQUEST"
export const GET_PENDING_REQUESTS = "GET_PENDING_REQUESTS"
export const GET_COMPLETE_REQUESTS = "GET_COMPLETE_REQUESTS"

// SETTINGS
export const GET_INFO = "GET_INFO"
export const GET_ADMIN = "GET_ADMIN"
export const GET_BILLING = "GET_BILLING"
export const UPDATE_FAIL = "UPDATE_FAIL"
export const UPDATE_INFO_SECCESS = "UPDATE_INFO_SECCESS"
export const UPDATE_ADMIN_SECCESS = "UPDATE_ADMIN_SECCESS"
export const UPDATE_BILLING_SECCESS = "UPDATE_BILLING_SECCESS"

// MESSAGES
export const SUBMIT_DEMO = "SUBMIT_DEMO"

// CLIENTS
export const GET_CLIENTS = "GET_CLIENTS"
export const CREATE_CLIENT = "CREATE_CLIENT"
